### ISSUE TITLE
plotting is not working

### ISSUE THREAD

**Issue by snap10** [ewrogers/burst-dockerfile#1]
The following command is supposed to work according to your readme
```
docker run -it -v $LOCAL_PATH:/mnt/burst ewrogers/burst-plotter:latest -k $WALLET_NUMERIC_ID -d /mnt/burst/plots -n 614400
```
However i get the following output
```
Using original algorithm.
Usage: ./plot -k KEY [ -x CORE ] [-d DIRECTORY] [-s STARTNONCE] [-n NONCES] [-m STAGGERSIZE] [-t THREADS] -a
   CORE:
     0 - default core
     1 - SSE2 core
   -a = ASYNC writer mode (will use 2x memory!)
```

What is broken here or am I missing something?

**Comment by ewrogers** [comment]
I think you need to specify a stagger size, I'll take a look at it.

**Comment by snap10** [comment]
I guess this had to do with a malformed numeric id -.-
Now everything seems fine =)

**Comment by darbs** [comment]
Hate to revive a dead issue but im having issues getting this working on osx, not sure if this is an issue with my ignorance of docker or an actual bug running this on osx. Every time i try running the command on an external drive i get 'File pre-allocation failed'.

Commands tried:
docker run -it -v /Volumes/BURST_0:/mnt/burst ewrogers/burst-plotter:latest -k 1 -x 2 -d /mnt/burst/plots -n 1179648 -m 32768 -s 0
docker run -it --mount type=bind,source=/Volumes/BURST_0,target=/mnt/burst ewrogers/burst-plotter:latest -k 1 -x 2 -d /mnt/burst/plots -n 1179648 -m 32768 -s 0

The volume does exist and i believe its about 309GB the drive itself is 320GB. I can see it on file explorer, its formatted under fat32. Im probably just missing something.

**Comment by ewrogers** [comment]
Feel free to create a new issue about this. Unfortunately I don't really plot much BURST lately but I can take a look at it.

**Comment by darbs** [comment]
Actually, I think it was a dumb mistake on my part. Fat32 only allows max 4gb file creation, so of course the allocation failed. I managed to get it working using a different plotter when i reformatted to extFat. Theoretically it should work with this one as well.
