### ISSUE TITLE
Appears Github changes are not reflected at Docker Hub

### ISSUE THREAD

**Issue by Lazuruz** [ewrogers/burst-dockerfile#3]
Docker Hub says latest is 7 months old despite more recent Github commits.  

Assuming this is the correct Docker Hub location: 
https://hub.docker.com/r/ewrogers/burst-plotter/

**Comment by ewrogers** [comment]
Yeah the plotter is somewhat dated.

I will be looking into it more once I get my new plotter set up in a week or so.

The plan is to have a CPU and GPU version of both.

**Comment by ewrogers** [comment]
Updated for Burstcoincg 2.2.1 wallet + CreepMiner 1.8.2

Changes are replicated across Docker hub as well.
