### ISSUE TITLE
Can't get the miner to recognize plot paths

### ISSUE THREAD

**Issue by FilipMlekicki** [ewrogers/burst-dockerfile#4]
I have a few drives connected to a Synology NAS, @ usbshare1/plots, usbshare2/plots, usbshare3/plots, and a folder home/plots on the NAS itself.

Have tried many combinations of paths in the config file and mount paths (based on available instructions) but still getting the error: plot file or dir does not exist or that there is an error somewhere in plots []. Program seems to still run after that but shows plot size as 0.0MB, and don't see any mining activity, but do see round winners.

Any help or clarifications would be greatly appreciated.

**Comment by ewrogers** [comment]
What does your `docker run` look like? Are you mounting the drives to the container?

**Comment by FilipWalkWell** [comment]
I am using the synology docker GUI, but mount the volumes as,       docker/mnt/miner/plots : /mnt/miner, and /usbshare1-2/plots : /mnt/disk1 . 

I have then tried both moving the plots files to /miner and keeping them in /miner/plots.

In the mining.conf file for plot paths i have tried, nothing, /plots, and the full directory /volume1/docker/mnt/miner/plots. 

Could you advise on how to setup both the run and config-file-plot-paths if my plots are in the folder docker/mnt/miner/plots and usbshare1-2/plots. Also would be helpful to know if i need to do anything special when running this using a Synology 713+ NAS drive.

**Comment by FilipWalkWell** [comment]
Any further info, or suggestions on what i might try?

**Comment by ewrogers** [comment]
Updated to creepMiner 1.8.2 with new configuration. If this issue continues please re-open a new issue.
